### ISSUE TITLE
How to use the Schedule Kit? 

### ISSUE THREAD

**Issue by vaibhav-kaushal** [opentok/schedulekit-php#21]
I have been trying to get this working but I am not able to. I tried installing kit on my local server but it did not work. Finally, I ran the "deploy to Heroku" link and it still does not work. Following is what happened with the heroku deployment after I registered on Heroku and Activated my account:

1. I clicked on the *Deploy to Heroku* button.
2. It opened up the screen to input the variables where I supplied the API key and secret my tokbox dashboard shows. 
3. Deployed the product. 

No errors were shown by Heroku and it reported the app as deployed. I launched the app's web address and it shows me a **404 Page Not Found** message. Are there other things that I am missing out here?

Video conferencing is quite important for me and I am looking to go for opentok if it works. Please help me get started here. 

Ragards

**Comment by aoberoi** [comment]
Let's try to solve the local server environment not working first. Heroku deployment is mostly there to serve the needs of mobile developers who have little interest in understanding the server code to work with the project. If you are in that boat, let me know and we can work on that instead.

*  Which web server are you using locally (Apache, nginx, etc)?
*  Are you getting a 404 response when you run the server locally?
*  Do you have server logs available? If so, can you share them so I can take a look to diagnose the issue?

**Comment by vaibhav-kaushal** [comment]
Hey, thanks for the answer. I figured this out. It was my mistake. I had to use the web directory contents only and I was trying to use the entire directory as it was.

**Comment by aoberoi** [comment]
no problem. glad you got it working.
