### ISSUE TITLE
web/templates/customer.php Form Not Showing

### ISSUE THREAD

**Issue by yugnats** [opentok/schedulekit-php#5]
Hi, after I install everything I am not seeing the form from the customer page (see attached). The DB table was created so there is a DB connection. I can also run the slim 'hello world' example with no issues.
![screen shot 2014-11-04 at 5 15 47 am](https://cloud.githubusercontent.com/assets/4109215/4906415/be2ab8fc-6458-11e4-9aa4-5b287888b0d7.png)

Thank you

**Comment by aoberoi** [comment]
@yugnats any luck?

**Comment by yugnats** [comment]
Hi Ankur, thank you for getting back to me. I haven't had a chance to try
it again. If I do I'll let u know what happens. Thanks!

**Comment by aoberoi** [comment]
okay no problem. i'm closing this issue for now, but feel free to reopen if you are still having a problem.

**Comment by yugnats** [comment]
Thank you!
